eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true


test:
  a: test-a
  b: test-b
  port: 7001
  host: 127.0.0.1