
server:
  port: 7999
spring:
  application:
    name: spring-cloud-template-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

zuul:
  ignored-services: "*"
  sensitive-headers:
#  routes:
#      auth:
#        path: /auth/**
#        serviceId: cloud-auth
#      user:
#        path: /course/**
#        serviceId: cloud-course
