server:
  port: 7001   # @TODO

spring:
  application:
    name: spring-cloud-template-center  ## @TODO

eureka:
  instance:
    hostname: localhost  ## @TODO
  client:
    service-url:
        default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
